### PR TITLE
`SEEDGEN_IMAGER_SKIP_RECERT` to skip recert validation

### PR DESCRIPTION
**Pull request by omertuc**
When the imager is launched through the `SeedGenerator` CR, we want the
to have the option to skip the recert stage of the seed image generation.

To that end this commit adds a new environment variable
`SEEDGEN_IMAGER_SKIP_RECERT` which when set to the value `TRUE`, will
make the `SeedGeneratorReconciler` ask the imager to skip recert
validation

This is useful when recert fails but we still want an image to be
created so that it can be shared for debugging and troubleshooting
purposes

### CODE REVIEW

**Comment by donpenney** [comment]
I don't think this should be a field in the CRD. Like with the precaching "best-effort" option, I'd go with an env var

**Comment by donpenney** [comment]
> I don't think this should be a field in the CRD. Like with the precaching "best-effort" option, I'd go with an env var

Maybe an env var like SEEDGEN_IMAGER_ADDITIONAL_ARGS, that the user could set whatever args they want? ie.
```
SEEDGEN_IMAGER_ADDITIONAL_ARGS="--skip-recert-validation --skip-cleanup"
```

**Comment by omertuc** [comment]
> > I don't think this should be a field in the CRD. Like with the precaching "best-effort" option, I'd go with an env var
> 
> Maybe an env var like SEEDGEN_IMAGER_ADDITIONAL_ARGS, that the user could set whatever args they want? ie.
> 
> ```
> SEEDGEN_IMAGER_ADDITIONAL_ARGS="--skip-recert-validation --skip-cleanup"
> ```

I wouldn't like to get into the business of separating args, it's non-trivial (you can't just split by space). I prefer dedicated environment variables.

Ideally I think the SeedGeneratorReconciler <-> ibu imager communication should also be done with a config file and or environment variables, instead of CLI which is made mostly for humans, so I wouldn't want to leak that CLI to the CR users in case we'll want to do remove that CLI in the future

**Review by donpenney — APPROVED** [review]

**Pull request merged**
