### PR TITLE
MGMT-16873: Change pull secret as part of recert reconfiguration

### PR DESCRIPTION
**Pull request by tsorya**
Post pivot will override the config.json in order to be able to pull recert image but recert will override all other places

Depends on https://github.com/rh-ecosystem-edge/recert/pull/100/files

### CODE REVIEW

**Comment by donpenney** [comment]
This will be great to have,,, thanks!

**Comment by tsorya** [comment]
recert was merged

**Review by eranco74 — COMMENTED** [review]
/lgtm

**Review by donpenney — APPROVED** [review]

**Pull request merged**
