### PR TITLE
Mgmt-15806: Get cluster attributes from kube-apiserver and save them to files in a directory

### PR DESCRIPTION
**Pull request by tsorya**
The cluster attributes gathered in this PR:

Cluster domain
Cluster ID
Pull Secret
IDMS

### CODE REVIEW

**Comment by tsorya** [comment]
replaces https://github.com/openshift-kni/lifecycle-agent/pull/8

**Comment by jc-rh** [comment]
Need to add a copy line for `internal` in the docker file

**Review by imiller0 — APPROVED** [review]
/lgtm

**Pull request merged**
