### PR TITLE
Add IBU Imager to LCA

### PR DESCRIPTION
**Pull request by donpenney**

### CODE REVIEW

**Comment by donpenney** [comment]
@jc-rh @leo8a For now, I've updated hack/lint.sh to skip ibu-imager. We'll need to take a look at resolving warnings, and make sure any other pieces function properly for ibu-imager living in a subdirectory

**Comment by leo8a** [comment]
This is just to confirm that I've tried the new packaging of the Imager tool (as a new entrypoint in the lifecycle-agent-operator container image) in my env, and it works as expected.

**Pull request merged**
