### PR TITLE
CNF-12652: bundle: Update csv annotations in LCA bundle

### PR DESCRIPTION
**Pull request by leo8a**
Sets `proxy-aware` and `fips-compliant` annotations to true in the LCA bundle, this will notify users installing LCA from the official catalogs about these operator's capabilities.

image

/cc @rauhersu @omertuc @jc-rh

### CODE REVIEW

**Comment by jc-rh** [comment]
should `disconnected` be true too?

**Comment by rauhersu** [comment]
/hold

We will need extra midstream changes to claim 'fips compliant'. I will let you know when ready. Additionally, I believe we should mimic those changes as part of the upstream build, to keep them both as symmetrical as we can.

**Comment by leo8a** [comment]
> should `disconnected` be true too?

yes, we do support LCA deployments in `disconnected` envs (also tested by QE)

**Pull request merged**
