### PR TITLE
MGMT-16652: add precache disabled and best effort support to ib-cli

### PR DESCRIPTION
**Pull request by tsorya**

### CODE REVIEW

**Comment by browsell** [comment]
Pre-caching failing in production is a fail.

There is already env variable to enable best effort for development purposes, https://github.com/openshift-kni/lifecycle-agent/blob/main/HACKING.md#setting-pre-caching-to-best-effort

**Comment by tsorya** [comment]
This is for ibi and not ibu.

**Review by eranco74 — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
