### PR TITLE
Update observedGeneration for conditions related to the current stage

### PR DESCRIPTION
**Pull request by jc-rh**

### CODE REVIEW

**Review by donpenney — COMMENTED** [review]
/lgtm

**Comment by sudomakeinstall2** [comment]
I am not sure how this helps. especially now that patches are disabled.

**Comment by Missxiaoguo** [comment]
> I am not sure how this helps. especially now that patches are disabled. If ibu is in idle and user patches spec (not stage) does the generation get synced using this?

Do we have all fields disabled now for patch? Probably not for i.e.,additionalImages?

**Comment by sudomakeinstall2** [comment]
@Missxiaoguo changes to oadpcontent, seedImageRef and extraManifests are blocked after transition to Prep.

**Pull request merged**
