### PR TITLE
MGMT-17283 - IBI - Run restorecon after mounting /var/lib/containers

### PR DESCRIPTION
**Pull request by javipolo**
/cc @donpenney 
/cc @eranco74

### CODE REVIEW

**Review by eranco74 — COMMENTED** [review]
/lgtm

**Comment by javipolo** [comment]
It makes more sense to run restorecon in the live ISO

please @eranco74 review again :sweat_smile: 

/unhold

**Comment by romfreiman** [comment]
Yea, lets understand first why is it need and not happens in IBU

**Comment by javipolo** [comment]
in IBU the directory/filesystem is created by ignition, which should properly handle the SELinux relabeling
in IBI the directory/filesystem is created by our tool, so we need to handle this first SELinux labeling

once the main directory /var/lib/containers are properly labeled, newly created files will inherit those labels, so this only needs to be done right after we mount it for the first time

this PR now handles exactly that case, labeling the empty /var/lib/containers while in RHCOS live iso, and this code is only run the first time, just before using /var/lib/containers for the first time

**Review by eranco74 — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
