### PR TITLE
Resync 4.15 with main

### PR DESCRIPTION
**Pull request by donpenney**
Due to the various refactoring since initially creating the release-4.15 branch, there is a large divergence compared to main. This PR realigns the release-4.15 branch fully with the main branch, up to: https://github.com/openshift-kni/lifecycle-agent/pull/493

The resync was done with `git merge -X theirs main`, followed by some additional manual resync to fully align and then reapply versioning changes.

This will need to coincide with a similar resync in recert. This PR will be put on hold until recert is ready.

The overall diff against main, as of 2024-05-08-15:30:00Z, is:
```
$ git diff main..resync-4.15-with-main
diff --git a/Dockerfile b/Dockerfile
index b6e3503..075b997 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -26,8 +26,7 @@ RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 GO111MODULE=on go build -mod=vendor -a

 #####################################################################################################
 # Build the operator image
-# note: update origin-cli-artifacts from `latest` to an appropriate OCP verison during release e.g `4.16`
-FROM quay.io/openshift/origin-cli-artifacts:latest AS origincli
+FROM quay.io/openshift/origin-cli-artifacts:4.15 AS origincli
 FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

 RUN if [[ ! -f /bin/nsenter ]]; then \
diff --git a/Makefile b/Makefile
index 2abe96a..08b1da2 100644
--- a/Makefile
+++ b/Makefile
@@ -3,7 +3,7 @@
 # To re-generate a bundle for another specific version without changing the standard setup, you can:
 # - use the VERSION as arg of the bundle target (e.g make bundle VERSION=0.0.2)
 # - use environment variables to overwrite this value (e.g export VERSION=0.0.2)
-VERSION ?= 4.16.0
+VERSION ?= 4.15.0

 # You can use podman or docker as a container engine. Notice that there are some options that might be only valid for one of them.
 ENGINE ?= docker
diff --git a/bundle/manifests/lifecycle-agent.clusterserviceversion.yaml b/bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
index a5a71b9..ac6f332 100644
--- a/bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
+++ b/bundle/manifests/lifecycle-agent.clusterserviceversion.yaml
@@ -56,7 +56,7 @@ metadata:
     features.operators.openshift.io/token-auth-aws: "false"
     features.operators.openshift.io/token-auth-azure: "false"
     features.operators.openshift.io/token-auth-gcp: "false"
-    olm.skipRange: '>=4.14.0 <4.16.0'
+    olm.skipRange: '>=4.14.0 <4.15.0'
     operatorframework.io/suggested-namespace: openshift-lifecycle-agent
     operatorframework.io/suggested-namespace-template: |-
       {
@@ -77,7 +77,7 @@ metadata:
     support: Red Hat
   labels:
     operatorframework.io/arch.amd64: supported
-  name: lifecycle-agent.v4.16.0
+  name: lifecycle-agent.v4.15.0
   namespace: openshift-lifecycle-agent
 spec:
   apiservicedefinitions: {}
@@ -615,7 +615,7 @@ spec:
                 - /usr/local/bin/manager
                 env:
                 - name: PRECACHE_WORKLOAD_IMG
-                  value: quay.io/openshift-kni/lifecycle-agent-operator:4.16.0
+                  value: quay.io/openshift-kni/lifecycle-agent-operator:4.15.0
                 - name: MY_POD_NAME
                   valueFrom:
                     fieldRef:
@@ -624,7 +624,7 @@ spec:
                   valueFrom:
                     fieldRef:
                       fieldPath: metadata.namespace
-                image: quay.io/openshift-kni/lifecycle-agent-operator:4.16.0
+                image: quay.io/openshift-kni/lifecycle-agent-operator:4.15.0
                 livenessProbe:
                   httpGet:
                     path: /healthz
@@ -722,4 +722,4 @@ spec:
   provider:
     name: Red Hat
   replaces: lifecycle-agent.v0.0.0
-  version: 4.16.0
+  version: 4.15.0
diff --git a/config/manager/kustomization.yaml b/config/manager/kustomization.yaml
index aaec521..2670852 100644
--- a/config/manager/kustomization.yaml
+++ b/config/manager/kustomization.yaml
@@ -13,6 +13,6 @@ configMapGenerator:
 images:
 - name: controller
   newName: quay.io/openshift-kni/lifecycle-agent-operator
-  newTag: 4.16.0
+  newTag: 4.15.0
 patches:
 - path: related-images/patch.yaml
diff --git a/config/manifests/bases/lifecycle-agent.clusterserviceversion.yaml b/config/manifests/bases/lifecycle-agent.clusterserviceversion.yaml
index c50bc49..b402cb1 100644
--- a/config/manifests/bases/lifecycle-agent.clusterserviceversion.yaml
+++ b/config/manifests/bases/lifecycle-agent.clusterserviceversion.yaml
@@ -17,7 +17,7 @@ metadata:
     features.operators.openshift.io/token-auth-aws: "false"
     features.operators.openshift.io/token-auth-azure: "false"
     features.operators.openshift.io/token-auth-gcp: "false"
-    olm.skipRange: '>=4.14.0 <4.16.0'
+    olm.skipRange: '>=4.14.0 <4.15.0'
     operatorframework.io/suggested-namespace: openshift-lifecycle-agent
     operatorframework.io/suggested-namespace-template: |-
       {
diff --git a/internal/common/consts.go b/internal/common/consts.go
index 5f3cfbb..5eec359 100644
--- a/internal/common/consts.go
+++ b/internal/common/consts.go
@@ -38,7 +38,7 @@ const (
        KubeconfigFile        = "/etc/kubernetes/static-pod-resources/kube-apiserver-certs/secrets/node-kubeconfigs/lb-ext.kubeconfig"

        RecertImageEnvKey      = "RELATED_IMAGE_RECERT_IMAGE"
-       DefaultRecertImage     = "quay.io/edge-infrastructure/recert:v0"
+       DefaultRecertImage     = "quay.io/edge-infrastructure/recert:release-4.15"
        EtcdStaticPodFile      = "/etc/kubernetes/manifests/etcd-pod.yaml"
        EtcdStaticPodContainer = "etcd"
        EtcdDefaultEndpoint    = "localhost:2379"
```

### CODE REVIEW

**Comment by donpenney** [comment]
/cc @browsell @omertuc @romfreiman
FYI

**Comment by leo8a** [comment]
pinning the recert PR also here to tie up both efforts

https://github.com/rh-ecosystem-edge/recert/pull/137

**Comment by donpenney** [comment]
The corresponding recert release-4.15 resync PR, https://github.com/rh-ecosystem-edge/recert/pull/137,  has merged, so this PR is now safe to merge as well

**Pull request merged**
