### PR TITLE
NO-ISSUE: handle case for static ip configuration without provide node ip (IBI) 

### PR DESCRIPTION
**Pull request by tsorya**
NO-ISSUE: In order to handle case for static ip configuration and without provided nodeip (IBI flow) we need to restart newtork manager before running nodeip configuration service.

# Background / Context

# Issue / Requirement / Reason for change

# Solution / Feature Overview

# Implementation Details

# Other Information

### CODE REVIEW

**Comment by leo8a** [comment]
```
error: failed to get network 'ib-orchestrate-1'
error: Network not found: no network with matching name 'ib-orchestrate-1' 
```
/test ibi-e2e-flow

**Review by javipolo — APPROVED** [review]

**Pull request merged**
