### PR TITLE
Upversion golang to 1.22

### PR DESCRIPTION
**Pull request by sudomakeinstall2**
# Background / Context

# Issue / Requirement / Reason for change

# Solution / Feature Overview

# Implementation Details

# Other Information

### CODE REVIEW

**Comment by rauhersu** [comment]
/hold

We need to incorporate these changes in downstream first, also you might want to take a look at openshift ci (if this has not been coordinated) as quay.io builds will likely need to update the builders too.

**Review by jc-rh — APPROVED** [review]

**Review by jc-rh — APPROVED** [review]

**Pull request merged**
