### PR TITLE
Enable additional golangci-lint plugins

### PR DESCRIPTION
**Pull request by donpenney**
Enabled the errorlint and loggercheck plugins, along with configuring the revive plugin to check for error messages that start with a capital letter.

### CODE REVIEW

**Comment by sudomakeinstall2** [comment]
`staticceck` that I am tryting to add  in https://github.com/openshift-kni/lifecycle-agent/pull/117 has error string capital check by default. But I can't fix the CI.

**Comment by donpenney** [comment]
Updated commit to address additional linter warnings in recently merged code

**Pull request merged**
