### PR TITLE
post-pivot - Cleanup seed's SriovFecNodeConfig CR if exists

### PR DESCRIPTION
**Pull request by leo8a**
In Telco deployments, the SRIOV-FEC operator may be deployed on the seed, and hence the seed's SriovFecNodeConfig CR would need to be cleaned up after pivoting.

Signed-off-by: Leonardo Ochoa-Aday <lochoa@redhat.com>

### CODE REVIEW

**Comment by leo8a** [comment]
/jira refresh
/hold 

testing it...

**Comment by browsell** [comment]
This is embedding speicif knowledge of an operator into LCA which is not desireable.

**Comment by leo8a** [comment]
closing as the SR-IOV operator is the one who should remove nodeState objects from non existing / nodes without a config-daemon

we can open again in the future if we finally decide to implement such cleaner in LCA (post-pivot)

**Pull request closed without merging**
