### PR TITLE
CNF-12605: move precache workload cli into lca-cli

### PR DESCRIPTION
**Pull request by pixelsoccupied**
A simple move from ./main to ./lca-cli to build precache in one shot 

/cc @donpenney @rauhersu @jc-rh

### CODE REVIEW

**Comment by pixelsoccupied** [comment]
/hold
need to coordinate with midstream!

**Comment by rauhersu** [comment]
Midstream changes underway, I will get back as soon as they are merged.

**Comment by rauhersu** [comment]
please, go ahead. Midstream changes already merged.

**Review by donpenney — APPROVED** [review]

**Pull request merged**
